export default {
  data() {
    return {
      // https://api.sheety.co/e39d8899-85e5-4281-acf4-4d854bd39994
      archetypeRepository: [
        {
          "label": "[4] Primaris Intercessor (60)",
          "name": "Primaris Intercessor",
          "cost": 60,
          "tier": 4,
          "species": "Primaris Astartes",
          "influence": 1,
          "keywords": "Imperium",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Adeptus Astartes",
          "avatar": null,
          "theme": "https://i.pinimg.com/originals/b6/ce/a4/b6cea48762622a3358b7fa0b8298a290.jpg",
          "key": "primarisIntercessor",
          "description": " ",
          "hint": "A skilled and focused warrior, adept at bringing death at range."
        },
        {
          "label": "[2] Space Marine Scout (20)",
          "name": "Space Marine Scout",
          "cost": 20,
          "tier": 2,
          "species": "Adeptus Astartes",
          "influence": 1,
          "keywords": "Imperium,Adeptus Astartes,<Chapter>",
          "bonus": null,
          "wargear": "Scout Armor,Boltgun||Bolt Pistol,Astartes combat knife,3 frag grenades",
          "abilities": "Use the Terrain",
          "keywordOption": "<Chapter>",
          "prerequisite": "Strength:3,Agility:3,Toughness:3,Ballistic Skill:2,Weapons Skill:2",
          "attributes": null,
          "skills": null,
          "group": "Adeptus Astartes",
          "avatar": null,
          "theme": null,
          "key": "spaceMarineScout",
          "description": null,
          "hint": "A stealthy warrior adept at reconnaissance."
        },
        {
          "label": "[3] Tactical Space Marine (50)",
          "name": "Tactical Space Marine",
          "cost": 50,
          "tier": 3,
          "species": "Adeptus Astartes",
          "influence": 2,
          "keywords": "Imperium,Adeptus Astartes,<Chapter>",
          "bonus": null,
          "wargear": "Aquila Power Armor, Boltgun, Boltpistol, Astartes Combat Knife, 3 Krak and Frag Grenades",
          "abilities": "Tactile versatility",
          "keywordOption": "<Chapter>",
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Adeptus Astartes",
          "avatar": null,
          "theme": "https://warhammerart.com/wp-content/uploads/2015/10/space-marines-codex-800x1200.jpg",
          "key": "tacticalSpaceMarine",
          "description": null,
          "hint": "A versatile warrior, veteran of a hundred battles."
        },
        {
          "label": "[3] Tech-Priest (60)",
          "name": "Tech-Priest",
          "cost": 60,
          "tier": 3,
          "species": "Human",
          "influence": 2,
          "keywords": "Imperium,Adeptus Mechanicus,Cult Mechanicus,<Forge World>",
          "bonus": null,
          "wargear": "Omnissian Axe,Laspistol,Augmentic aervo-arm,<augmentic>,<augmentic>,Light power Armour",
          "abilities": "Rite of Repair",
          "keywordOption": "<Forge World>",
          "prerequisite": "Intellect:3,Tech:3,Scholar:1",
          "attributes": null,
          "skills": null,
          "group": "Adeptus Mechanicus",
          "avatar": null,
          "theme": null,
          "key": "techPriest",
          "description": null,
          "hint": "A priest of the Omnissiah, able to commune with the machine-spirits."
        },
        {
          "label": "[2] Death Cult Assassin (20)",
          "name": "Death Cult Assassin",
          "cost": 20,
          "tier": 2,
          "species": "Human",
          "influence": 0,
          "keywords": "Imperium,Adeptus Ministorum",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": "Agility:4,Weapon Skill:2",
          "attributes": null,
          "skills": null,
          "group": "Adeptus Ministorum",
          "avatar": null,
          "theme": null,
          "key": "deathCultAssassin",
          "description": null,
          "hint": "An agile killer, expressing worship through the art of death."
        },
        {
          "label": "[1] Sister Hospitaller (0)",
          "name": "Sister Hospitaller",
          "cost": 0,
          "tier": 1,
          "species": "Human",
          "influence": 0,
          "keywords": "Imperium,Adeptus Ministorum,Adeptus Sororitas,<Order>",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": "<Order>",
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Adeptus Sororitas",
          "avatar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrrCEl2BdBEHp_7h8k9aenXxDlhqNeLRwtzcvRv-XLMKgSpHOi",
          "theme": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/6e73e8db-4ce5-41da-83f7-1961673f2bf4/d3bb03b-ea084fd3-bd27-484c-8dbe-4c0e6d77870c.jpg/v1/fill/w_786,h_1017,q_70,strp/sister_hospitaller_by_pvtserrano_d3bb03b-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTE2NSIsInBhdGgiOiJcL2ZcLzZlNzNlOGRiLTRjZTUtNDFkYS04M2Y3LTE5NjE2NzNmMmJmNFwvZDNiYjAzYi1lYTA4NGZkMy1iZDI3LTQ4NGMtOGRiZS00YzBlNmQ3Nzg3MGMuanBnIiwid2lkdGgiOiI8PTkwMCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.MIutz9zhcYbaYR-pw_fmLIc8OiaFdOWwdlfVl8oQ5fw",
          "key": "sisterHospitaller",
          "description": null,
          "hint": "A pious healer dedicated to care of both body and soul."
        },
        {
          "label": "[2] Sister of Battle (40)",
          "name": "Sister of Battle",
          "cost": 40,
          "tier": 2,
          "species": "Human",
          "influence": 1,
          "keywords": "Imperium,Adeptus Ministorum,Adeptus Sororitas,<Order>",
          "bonus": null,
          "wargear": "Sororitas Power Armour,Chaplet Ecclisiasticus,Boltgun||Chainsword+Bolt Pistol,clothing,writing kit,copy of the Rule of the Sororitas",
          "abilities": "Purity of Faith",
          "keywordOption": "<Order>",
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Adeptus Sororitas",
          "avatar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrrCEl2BdBEHp_7h8k9aenXxDlhqNeLRwtzcvRv-XLMKgSpHOi",
          "theme": "https://66.media.tumblr.com/c165dd55e4ffdb6900c28eae2632a020/tumblr_ngd0c9F5R61tvfheeo1_500.jpg",
          "key": "sisterOfBattle",
          "description": "As the militant arm of the of the Adeptus Ministorum, the Sisters of Battle are equipped to engage any who would dare to oppose the Imperial Creed. It is their sacred duty to cleanse the galaxy of heresy and corruption, wherever they should fi nd it, including within the various organisations of the Imperium of Man. Due to their shared goals, the Orders Militant often work in conjunction with the Imperial Inquisition, though they remain distinct organisations. Many of the orders maintain convents on Shrine Worlds, so that they can more easily defend those places most blessed to the Imperial Creed.",
          "hint": "A determined warrior, filled with purity and faith."
        },
        {
          "label": "[1] Corsairs (0)",
          "name": "Corsairs",
          "cost": 0,
          "tier": 1,
          "species": "Eldar",
          "influence": 0,
          "keywords": "Aeldari,Anhrathe,<Coterie>",
          "bonus": null,
          "wargear": null,
          "abilities": "Dancing the Blade's Edge",
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Aeldari",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A space-faring pirate of an ancient race."
        },
        {
          "label": "[2] Ranger (30)",
          "name": "Ranger",
          "cost": 30,
          "tier": 2,
          "species": "Eldar",
          "influence": 0,
          "keywords": "Aeldari,Asuryani,<Crafsworld>",
          "bonus": null,
          "wargear": null,
          "abilities": "From the Shadows",
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Aeldari",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A wanderer, a scout, and tracker for the good of their people."
        },
        {
          "label": "[3] Warlock (80)",
          "name": "Warlock",
          "cost": 80,
          "tier": 3,
          "species": "Eldar",
          "influence": 2,
          "keywords": "Aeldari,Asuryani,Psyker,<Crafsworld>",
          "bonus": null,
          "wargear": null,
          "abilities": "Runes of Battle",
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Aeldari",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A powerful psyker, wielding strictly-guided powers for the Aeldari cause."
        },
        {
          "label": "[1] Inquisitorial Acolyte (0)",
          "name": "Inquisitorial Acolyte",
          "cost": 0,
          "tier": 1,
          "species": "Human",
          "influence": 2,
          "keywords": "Imperium,Inquisition,<ANY>,<Ordo>",
          "bonus": null,
          "wargear": "Flak Armor,<Ranged Weapon:5:Uncommon>,Knife,Symbol of authority",
          "abilities": "Inquisitorial Decree",
          "keywordOption": "<Ordo>",
          "prerequisite": "Any:2",
          "attributes": null,
          "skills": null,
          "group": "Agents of the Imperium",
          "avatar": "rwqrw",
          "theme": null,
          "key": "inquisitorialAcolyte",
          "description": null,
          "hint": "A representative of the Inquisition, adaptable and possessing great potential."
        },
        {
          "label": "[1] Inquisitorial Adept (0)",
          "name": "Inquisitorial Adept",
          "cost": 0,
          "tier": 1,
          "species": "Human",
          "influence": 1,
          "keywords": "Imperium,Inquisition,<Ordo>",
          "bonus": null,
          "wargear": "Flak Armor,Laspistol,Knife,Auto quill,data-slate,3 scrolls of ancient records",
          "abilities": "Administratum Records",
          "keywordOption": "<Ordo>",
          "prerequisite": "Intellect:3,Scholar:2",
          "attributes": null,
          "skills": null,
          "group": "Agents of the Imperium",
          "avatar": null,
          "theme": null,
          "key": "inquisitorialAdept",
          "description": null,
          "hint": "A learned scholar and scribe, adept at navigating bureaucratic obstacles."
        },
        {
          "label": "[2] Rogue Trader (40)",
          "name": "Rogue Trader",
          "cost": 40,
          "tier": 2,
          "species": "Human",
          "influence": 2,
          "keywords": "Imperium,Rogue Trader,<Dynasty>",
          "bonus": null,
          "wargear": "Flak Coat||Carapace Armor||Light Power Armor,Imperial Frigate,<Melee ,<Melee Weapon:Tier+4:Rare>,<Ranged Weapon:Tier+4:Rare>",
          "abilities": "Warrant of Trade",
          "keywordOption": "<Dynasty>",
          "prerequisite": "Fellowship:3,Cunning:1,Insight:2,Persuasion:2,Awareness:1",
          "attributes": null,
          "skills": null,
          "group": "Agents of the Imperium",
          "avatar": null,
          "theme": null,
          "key": "rogueTrader",
          "description": null,
          "hint": "An adventuresome and infl uential explorer with their own space vessel."
        },
        {
          "label": "[2] Sanctioned Psyker (50)",
          "name": "Sanctioned Psyker",
          "cost": 50,
          "tier": 2,
          "species": "Human",
          "influence": 0,
          "keywords": "Imperium,Adptus Astartes Telepathica,Psyker,Scholastica Psykana",
          "bonus": null,
          "wargear": "Laspistol,Force rod,Psykana Mercy  Blade,Guard issue mess kit,blanket,grooming kit,2 ration packs",
          "abilities": "Psyker (Sanctioned)",
          "keywordOption": null,
          "prerequisite": "Willpower:4,Psychic Mastery:1",
          "attributes": null,
          "skills": null,
          "group": "Agents of the Imperium",
          "avatar": null,
          "theme": null,
          "key": "sanctionedPsyker",
          "description": null,
          "hint": "Able to focus the warp through their mind, they are blessed or cursed with psychic powers."
        },
        {
          "label": "[3] Commissar (50)",
          "name": "Commissar",
          "cost": 50,
          "tier": 3,
          "species": "Human",
          "influence": 3,
          "keywords": "Imperium,Astra Militarum,Officio Prefectus",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Astra Militarum",
          "avatar": null,
          "theme": null,
          "key": "commissar",
          "description": null,
          "hint": "A fearsome leader, inspiring both dread and respect in great measure."
        },
        {
          "label": "[1] Imperial Guardsman (0)",
          "name": "Imperial Guardsman",
          "cost": 0,
          "tier": 1,
          "species": "Human",
          "influence": 0,
          "keywords": "Imperium,Astra Militarum,<Regiment>",
          "bonus": null,
          "wargear": "Flak Armour, lasgun, knife, guard issue mess kit, blanket, grooming kit, Uplifting Primer,3 ration packs.",
          "abilities": "Look Out Sir",
          "keywordOption": "<Regiment>",
          "prerequisite": "Ballistik Skill:2",
          "attributes": null,
          "skills": "Ballistik Skill:2",
          "group": "Astra Militarum",
          "avatar": null,
          "theme": "archetype_imperial-guardsman.jpg",
          "key": "imperialGuardsman",
          "description": null,
          "hint": "A disciplined soldier, used to fi ghting amid multitudes"
        },
        {
          "label": "[2] Tempestus Scion (30)",
          "name": "Tempestus Scion",
          "cost": 30,
          "tier": 2,
          "species": "Human",
          "influence": 1,
          "keywords": "Imperium,Astra Militarum,Militarum Tempest",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": "Initiative:3,Strength:3,Toughness:3,Ballistik Skill:2,Stealth:2",
          "attributes": null,
          "skills": null,
          "group": "Astra Militarum",
          "avatar": null,
          "theme": null,
          "key": "tempestusScion",
          "description": null,
          "hint": "An elite, highly-trained soldier, used to undertaking special missions."
        },
        {
          "label": "[1] Boy (0)",
          "name": "Boy",
          "cost": 0,
          "tier": 1,
          "species": "Ork",
          "influence": 0,
          "keywords": "Ork,<Clan>",
          "bonus": null,
          "wargear": "Shoota,Slugga,Choppa",
          "abilities": "Get Stuck In",
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Orks",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A brutish warrior and thug who believes that might makes right."
        },
        {
          "label": "[2] Kommando (30)",
          "name": "Kommando",
          "cost": 30,
          "tier": 2,
          "species": "Ork",
          "influence": 0,
          "keywords": "Ork,<Clan>",
          "bonus": null,
          "wargear": "Shoota,Slugga,Choppa,Stickbombs",
          "abilities": "Kunnin' Plan",
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Orks",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A stealthy and cunning warrior who knows how to turn almost any battle to his advantage."
        },
        {
          "label": "[3] Nob (60)",
          "name": "Nob",
          "cost": 60,
          "tier": 3,
          "species": "Ork",
          "influence": 2,
          "keywords": "Ork,<Clan>",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Orks",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A savage warrior and capable leader, using brute force to succeed where others fail."
        },
        {
          "label": "[3] Chaos Space Marine (50)",
          "name": "Chaos Space Marine",
          "cost": 50,
          "tier": 3,
          "species": "Adeptus Astartes",
          "influence": 2,
          "keywords": "Chaos,Heretic,Heretic Astartes,<Mark of Chaos>,<Legion>",
          "bonus": "Corruption,Corruption,Corruption",
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Renegades",
          "avatar": null,
          "theme": null,
          "key": "chaosSpaceMarine",
          "description": null,
          "hint": "A renegade warrior and death-dealer, a dark refl ection of their noble brethren."
        },
        {
          "label": "[1] Cultist (0)",
          "name": "Cultist",
          "cost": 0,
          "tier": 1,
          "species": "Human",
          "influence": 2,
          "keywords": "Chaos,Heretic,Heretic Astartes,<Mark of Chaos>,<Any>",
          "bonus": "Corruption",
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": "Deception:1",
          "attributes": null,
          "skills": null,
          "group": "Renegades",
          "avatar": null,
          "theme": null,
          "key": "cultist",
          "description": null,
          "hint": "A disciple of the Ruinous Powers, eager to gain their capricious favour."
        },
        {
          "label": "[2] Heretek (60)",
          "name": "Heretek",
          "cost": 60,
          "tier": 2,
          "species": "Human",
          "influence": 1,
          "keywords": "Chaos,Heretic,Adeptus Mechanicus,Dark Mechanicus",
          "bonus": "Corruption,Corruption,Corruption",
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Renegades",
          "avatar": null,
          "theme": null,
          "key": "heretek",
          "description": null,
          "hint": "A tinkerer, corruptor of machine-spirits, a bearer of the sin of innovation."
        },
        {
          "label": "[2] Rogue Psyker (50)",
          "name": "Rogue Psyker",
          "cost": 50,
          "tier": 2,
          "species": "Human",
          "influence": 0,
          "keywords": "Chaos,Heretic,Psyker",
          "bonus": "Corruption,Corruption,Corruption",
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Renegades",
          "avatar": null,
          "theme": null,
          "key": "roguePsyker",
          "description": null,
          "hint": "An unsanctioned bearer of psychic powers, wielding the warp’s power without discipline."
        },
        {
          "label": "[1] Ganger (0)",
          "name": "Ganger",
          "cost": 0,
          "tier": 1,
          "species": "Human",
          "influence": 1,
          "keywords": "Scum,<ANY>",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": "<Any>",
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Scum",
          "avatar": null,
          "theme": null,
          "key": "hiveGanger",
          "description": null,
          "hint": "A resourceful and tenacious survivor from the depths of enormous industrial cities."
        },
        {
          "label": "[2] Skitarius (40)",
          "name": "Skitarius",
          "cost": 40,
          "tier": 2,
          "species": "Human",
          "influence": 0,
          "keywords": "Imperium,Adeptus Mechanicus,Skitarii,<Forge World>",
          "bonus": null,
          "wargear": "Galvanic rifle,Skitarii auto-curiass",
          "abilities": "Heavily Augmented",
          "keywordOption": "<Forge World>",
          "prerequisite": "Toughness:3,Ballistik Skill:2,Tech:1",
          "attributes": "Toughness:3",
          "skills": "Ballistik Skill:2,Tech:1",
          "group": "Adeptus Mechanicus",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A warrior of the Machine Cult, sturdy and reliable."
        },
        {
          "label": null,
          "name": "Ministorum Priest",
          "cost": 0,
          "tier": 1,
          "species": "Human",
          "influence": 1,
          "keywords": "Imperium,Adeptus Ministorum",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Adeptus Ministorum",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A zealous preacher of the Imperial Creed."
        },
        {
          "label": null,
          "name": "Crusader",
          "cost": 40,
          "tier": 3,
          "species": "Human",
          "influence": 1,
          "keywords": "Imperium,Adeptus Ministorum",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Adeptus Ministorum",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A holy warrior with unfl agging devotion to the God-Emperor."
        },
        {
          "label": null,
          "name": "Scavvy",
          "cost": 10,
          "tier": 2,
          "species": "Human",
          "influence": null,
          "keywords": "Imperium,Scum",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Scum",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A mutant—cast out and reviled—yet their mutations give them power."
        },
        {
          "label": null,
          "name": "Desperado",
          "cost": 40,
          "tier": 3,
          "species": "Human",
          "influence": null,
          "keywords": "Imperium,Scum",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Scum",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A savvy and dangerous bounty hunter, mercenary, and gun for hire."
        },
        {
          "label": null,
          "name": "Inquisitor",
          "cost": 70,
          "tier": 4,
          "species": "Human",
          "influence": null,
          "keywords": "Imperium,",
          "bonus": null,
          "wargear": null,
          "abilities": null,
          "keywordOption": null,
          "prerequisite": null,
          "attributes": null,
          "skills": null,
          "group": "Agents of the Imperium",
          "avatar": null,
          "theme": null,
          "key": null,
          "description": null,
          "hint": "A bearer of profound Imperial authority, adept at discovering the truth in the shadows."
        }
      ],
      // https://api.sheety.co/6790490e-d9cc-439f-839b-dec3f1f8edc0
      archetypeAbilityRepository: [
        {
          "label": "Purity of Faith",
          "name": "Purity of Faith",
          "archetype": "Sisters of Battle",
          "rules": "Sisters of Battle and any allies within 15 meters and line of sight add +Rank to Corruption Tests. Sisters of Battle gain +Rank to any dice pool to resist psychic powers and effects.",
          "affects": "Corruption Tests",
          "effect": "Sisters of Battle and any allies within 15 meters and line of sight add +Rank to Corruption Tests. Sisters of Battle gain +Rank to any dice pool to resist psychic powers and effects."
        },
        {
          "label": "Inquisitorial Decree",
          "name": "Inquisitorial Decree",
          "archetype": null,
          "rules": "Once per scene, an Inquisitorial Acolyte may invoke the name of their Inquisitor to gain +Rank to an Infl uence or Interaction Skill test involving a being with the Imperium keyword.",
          "affects": null,
          "effect": "Once per scene, an Inquisitorial Acolyte may invoke the name of their Inquisitor to gain +Rank to an Infl uence or Interaction Skill test involving a being with the Imperium keyword."
        },
        {
          "label": "Warrant of Trade",
          "name": "Warrant of Trade",
          "archetype": null,
          "rules": "Rogue Traders are masters at manipulating situations to their advantage. They receive +Rank to all Persuasion tests and Influence tests to acquire goods or services.",
          "affects": null,
          "effect": "Rogue Traders are masters at manipulating situations to their advantage. They receive +Rank to all Persuasion tests and Influence tests to acquire goods or services."
        },
        {
          "label": "Rite of Repair",
          "name": "Rite of Repair",
          "archetype": null,
          "rules": "Rite of Repair",
          "affects": null,
          "effect": null
        },
        {
          "label": "Get Stuck In",
          "name": "Get Stuck In",
          "archetype": "Boy",
          "rules": "A Boy gains +Rank to melee attacks for every ally engaged in melee combat with the same target.",
          "affects": null,
          "effect": null
        },
        {
          "label": "Kunnin' Plan",
          "name": "Kunnin' Plan",
          "archetype": "Kommando",
          "rules": "A Kommando and any allies with the Ork Keyword within 15 metres gain +1/2 Rank to Stealth tests.",
          "affects": null,
          "effect": null
        }
      ],
    }
  }
};
