export default {
  data() {
    return {
      // https://api.sheety.co/cd93dfab-c658-4099-8a93-e6cc202b3488
      wargearRepository: [
        {
          "key": null,
          "name": "Aquila Mk VII",
          "type": "Armour",
          "subtype": "Astartes Armour",
          "value": 8,
          "rarity": "Very Rare",
          "keywords": "Powered,Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Scout Armour",
          "type": "Armour",
          "subtype": "Astartes Armour",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Tacticus Mk X",
          "type": "Armour",
          "subtype": "Astartes Armour",
          "value": 9,
          "rarity": "Very Rare",
          "keywords": "Powered,Imperium,Adeptus Astartes,Primaris",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Terminator Armour",
          "type": "Armour",
          "subtype": "Astartes Armour",
          "value": 10,
          "rarity": "Unique",
          "keywords": "Powered,Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Arm",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 4,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": "Strength:1",
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Auger Eye",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": "Awareness:1",
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Legs",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 4,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": "Speed:2m",
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Night Eye",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": "Prysense Googles (5 Rare)",
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Pict Recorder",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": "Recorder",
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Respirator",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 5,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Reticule Eye",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": "Ballistik Skill:1",
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Telescopic Eye",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": "No Distance Penalty",
          "source": null
        },
        {
          "key": null,
          "name": "Augmetic Visceral",
          "type": "Cybernetic",
          "subtype": "Augmetic",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "<Any>",
          "effect": "Toughness:1,Wound:1",
          "source": null
        },
        {
          "key": null,
          "name": "Bodyglove",
          "type": "Armour",
          "subtype": "Basic",
          "value": 3,
          "rarity": "Rare",
          "keywords": "Light,Imperium,Adeptus Ministorum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Carapace Armour",
          "type": "Armour",
          "subtype": "Basic",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Imperium,Officio Assassinorum,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Flak Armour",
          "type": "Armour",
          "subtype": "Basic",
          "value": 4,
          "rarity": "Common",
          "keywords": "Flak,Imeprium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Flak Coat",
          "type": "Armour",
          "subtype": "Basic",
          "value": 4,
          "rarity": "Uncommon",
          "keywords": "Flak,Imeprium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mesh Armour",
          "type": "Armour",
          "subtype": "Basic",
          "value": 3,
          "rarity": "Rare",
          "keywords": "Light,Imperium,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Primitive Armour",
          "type": "Armour",
          "subtype": "Basic",
          "value": 2,
          "rarity": "Common",
          "keywords": "Heavy,Primitive",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Skitarii Auto-Cuirass",
          "type": "Armour",
          "subtype": "Basic",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Heavy,Imperium,Adeptus Mechanicus,Skitarii",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Tempestus Carapace",
          "type": "Armour",
          "subtype": "Basic",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Heavy,Imeprium,Astra Militarum,Militarum Tempestus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Assault Bolter",
          "type": "Ranged Weapon",
          "subtype": "Bolt Weapon",
          "value": 8,
          "rarity": "Very Rare",
          "keywords": "Bolt,Imperium,Adeptus Astartes,Primaris",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Bolt Pistol",
          "type": "Ranged Weapon",
          "subtype": "Bolt Weapon",
          "value": 4,
          "rarity": "Uncommon",
          "keywords": "Bolt,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Bolt Rifle",
          "type": "Ranged Weapon",
          "subtype": "Bolt Weapon",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Bolt,Imperium,Adeptus Astartes,Primaris",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Boltgun",
          "type": "Ranged Weapon",
          "subtype": "Bolt Weapon",
          "value": 4,
          "rarity": "Uncommon",
          "keywords": "Bolt,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Heavy Bolt Pistol",
          "type": "Ranged Weapon",
          "subtype": "Bolt Weapon",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Bolt,Imperium,Adeptus Astartes,Primaris",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Heavy Bolter",
          "type": "Ranged Weapon",
          "subtype": "Bolt Weapon",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Bolt,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Storm Bolter",
          "type": "Ranged Weapon",
          "subtype": "Bolt Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Bolt,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chain Axe",
          "type": "Melee Weapon",
          "subtype": "Chain Weapon",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Chain,Chaos",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chain Bayonet",
          "type": "Melee Weapon",
          "subtype": "Chain Weapon",
          "value": 4,
          "rarity": "Rare",
          "keywords": "Chain,Imperium,Chaos",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chain Fist",
          "type": "Melee Weapon",
          "subtype": "Chain Weapon",
          "value": 10,
          "rarity": "Very Rare",
          "keywords": "Chain,Power Field,Imperium,Chaos,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chain Sword",
          "type": "Melee Weapon",
          "subtype": "Chain Weapon",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Chain,Aeldari,Imperium,Chaos",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Eviscerator",
          "type": "Melee Weapon",
          "subtype": "Chain Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Chain,Adeptus Ministorum,Adepta Sororitas,Two-Handed",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Corsair Armour",
          "type": "Armour",
          "subtype": "Eldar Armour",
          "value": 3,
          "rarity": "Rare",
          "keywords": "Light,Aeldari,Anhrathe",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Eldar Mesh Armour",
          "type": "Armour",
          "subtype": "Eldar Armour",
          "value": 4,
          "rarity": "Very Rare",
          "keywords": "Light,Aeldari,Asuryani",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Heavy Mesh Armour",
          "type": "Armour",
          "subtype": "Eldar Armour",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Aeldari, Anhrathe",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Rune Armour",
          "type": "Armour",
          "subtype": "Eldar Armour",
          "value": 6,
          "rarity": "Unique",
          "keywords": "Force Field,Aeldari,Asuryani",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Shimmershield",
          "type": "Armour",
          "subtype": "Eldar Armour",
          "value": 7,
          "rarity": "Unique",
          "keywords": "Force Field,Aeldari,Asuryani",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Voidplate Harness",
          "type": "Armour",
          "subtype": "Eldar Armour",
          "value": 7,
          "rarity": "Rare",
          "keywords": "Aeldari,Anhrathe",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Bonesinger Shard",
          "type": "Tools & Equipment",
          "subtype": "Eldar Equipment",
          "value": 6,
          "rarity": null,
          "keywords": "Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Spirit Stone",
          "type": "Tools & Equipment",
          "subtype": "Eldar Equipment",
          "value": 7,
          "rarity": null,
          "keywords": "Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Webway Keystone",
          "type": "Tools & Equipment",
          "subtype": "Eldar Equipment",
          "value": 7,
          "rarity": null,
          "keywords": "Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Singing Spear",
          "type": "Melee Weapon",
          "subtype": "Eldar Melee Weapon",
          "value": 11,
          "rarity": "Unique",
          "keywords": "Force, Aeldari, Asuryani",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Witchblade",
          "type": "Melee Weapon",
          "subtype": "Eldar Melee Weapon",
          "value": 9,
          "rarity": "Very Rare",
          "keywords": "Force, Aeldari, Asuryani",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Fusion Gun",
          "type": "Ranged Weapon",
          "subtype": "Eldar Ranged Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Melta,Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Lasblaster",
          "type": "Ranged Weapon",
          "subtype": "Eldar Ranged Weapon",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Las,Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ranger Long Rifle",
          "type": "Ranged Weapon",
          "subtype": "Eldar Ranged Weapon",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Las,Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Shuriken Catapult",
          "type": "Ranged Weapon",
          "subtype": "Eldar Ranged Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Shuriken,Aeldari,Asuryan",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Shuriken Pistol",
          "type": "Ranged Weapon",
          "subtype": "Eldar Ranged Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Shuriken,Aeldari,Asuryan",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Neural Whip",
          "type": "Melee Weapon",
          "subtype": "Exotic Melee Weapon",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Exotic,Chaos,Inquisition",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Shock Maul",
          "type": "Melee Weapon",
          "subtype": "Exotic Melee Weapon",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Exotic,Imperium,Adeptus Arbites",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Shock Whip",
          "type": "Melee Weapon",
          "subtype": "Exotic Melee Weapon",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Exotic,Scum,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Whip",
          "type": "Melee Weapon",
          "subtype": "Exotic Melee Weapon",
          "value": 2,
          "rarity": "Common",
          "keywords": "Primitive,Imperium,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Arc Pistol",
          "type": "Ranged Weapon",
          "subtype": "Exotic Ranged Weapon",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Arc,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Arc Rifle",
          "type": "Ranged Weapon",
          "subtype": "Exotic Ranged Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Arc,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Galvanic Rifle",
          "type": "Ranged Weapon",
          "subtype": "Exotic Ranged Weapon",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Projectile,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Radium Carbine",
          "type": "Ranged Weapon",
          "subtype": "Exotic Ranged Weapon",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Projectile,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Radium Pistol",
          "type": "Ranged Weapon",
          "subtype": "Exotic Ranged Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Projectile,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Flamer",
          "type": "Ranged Weapon",
          "subtype": "Flame Weapon",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Fire,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Hand Flamer",
          "type": "Ranged Weapon",
          "subtype": "Flame Weapon",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Fire,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Heavy Flamer",
          "type": "Ranged Weapon",
          "subtype": "Flame Weapon",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Fire,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Rosarius",
          "type": "Armour",
          "subtype": "Force Shield",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Force Field,Imperium,Adeptus Astartes,Adeptus Ministorum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Storm Shield",
          "type": "Armour",
          "subtype": "Force Shield",
          "value": 8,
          "rarity": "Unique",
          "keywords": "Force Field,Imperium,Adeptus Astartes,Adeptus Ministorum,Inquisition",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Refractor Field",
          "type": "Armour",
          "subtype": "Force Shields",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Force Field,Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Force Axe",
          "type": "Melee Weapon",
          "subtype": "Force Weapon",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Force,Imperium,Inquisition,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Force Hammer",
          "type": "Melee Weapon",
          "subtype": "Force Weapon",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Force,Two-Handed,Imperium,Inquisition,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Force Rod",
          "type": "Melee Weapon",
          "subtype": "Force Weapon",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Force,Two-Handed,Imperium,Inquisition,Adeptus Astartes,Adeptus Astra Telephatica",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Force Sword",
          "type": "Melee Weapon",
          "subtype": "Force Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Force,Imperium,Inquisition,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Militarum Tempestus Grenade Launcher",
          "type": "Ranged Weapon",
          "subtype": "Grenade Launcher",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Explosive,Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Voss Pattern Grenade Launcher",
          "type": "Ranged Weapon",
          "subtype": "Grenade Launcher",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Explosive,Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Frag Grenade",
          "type": "Ranged Weapon",
          "subtype": "Grenades",
          "value": 2,
          "rarity": "Uncommon",
          "keywords": "Explosive,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Krak Grenade",
          "type": "Ranged Weapon",
          "subtype": "Grenades",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Explosive,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Plasma Grenade",
          "type": "Ranged Weapon",
          "subtype": "Grenades",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Explosive,Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "9-70 Entrenching Tool",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Common",
          "keywords": "Imperium,Astra Militarum",
          "effect": "Halves time to dig trenches, foxholes, fortifications.",
          "source": 306
        },
        {
          "key": null,
          "name": "Auspex",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium,Adeptus Mechanicus",
          "effect": "Detects energy emissions, motion and life sins up to 50m. +2 dice to Awareness Tests",
          "source": null
        },
        {
          "key": null,
          "name": "Auto Quill",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 4,
          "rarity": "Uncommon",
          "keywords": "Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ballistic Appeasement Auto-Reliquary",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Imperium,Adeptus Astartes,Primaris",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chameleoline Cloak",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chaplet Ecclesiasticus",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Imperium,Adeptus Ministorum,Adepta Sororitas",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chirurgeon's Tools Medkit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium,Adepta Sororitas",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chrono",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Common",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Clothing (Common)",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 1,
          "rarity": "Common",
          "keywords": "<Any>",
          "effect": "Various styles and cut of clothing can be found across countless worlds in the 41st Millennium.",
          "source": null
        },
        {
          "key": null,
          "name": "Clothing (Rare)",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Clothing (Uncommon)",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Combi-Tool",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Data-Slate",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Common",
          "keywords": "Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Diagnostor",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Grav-Chute",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Jump Pack",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 7,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Magnoculars",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Martyr's Gift Variant Medkit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Medikit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Missionary Kit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Rare",
          "keywords": "Imperium,Adeptus Ministorum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Munitorum-Issue Mess Kit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Common",
          "keywords": "Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Periculum Kit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Preysense Goggles",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Psychic Focus",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ration Packs",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 1,
          "rarity": "Common",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Respirator",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Unommon",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Rule of the Sororitas",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Uncommon",
          "keywords": "Imperium,Adepta Sororitas",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Sacred Machine Oil",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Imperium,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Slate Monitron",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Stimm",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 4,
          "rarity": "Uncommon",
          "keywords": "Imperium,Scun",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Survival Kit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Symbol of Authority",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Uplifting Primer",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Common",
          "keywords": "Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Void Suit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 5,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Vox",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Writing Kit",
          "type": "Tools & Equipment",
          "subtype": "Imperial Equipment",
          "value": 2,
          "rarity": "Common",
          "keywords": "Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Auger Array",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 4,
          "rarity": "Rare",
          "keywords": "Imperium,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Autodogmatic Cortex",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Imperium,Adeptus Mechanicus,Adaptus Ministorum",
          "effect": "Willpower:1",
          "source": null
        },
        {
          "key": null,
          "name": "Cardioproxy",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 6,
          "rarity": "Unique",
          "keywords": "<Any>",
          "effect": "Toughness:1,Defiance:1",
          "source": null
        },
        {
          "key": null,
          "name": "Cortex Implant",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "<Any>",
          "effect": "Intellect:1",
          "source": null
        },
        {
          "key": null,
          "name": "Mechandrites (Ballistic)",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mechandrites (Exploration)",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mechandrites (Medicae)",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mechandrites (Optical)",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mechandrites (Servo-Arm)",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mind Impulse Unit",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium,Inquisition,Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Neuroplastic Psychosectemy",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 7,
          "rarity": "Unique",
          "keywords": "Adeptus Mechanicus",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Reflex Catalyst",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "<Any>",
          "effect": "Initiative:1",
          "source": null
        },
        {
          "key": null,
          "name": "Sinew Armature",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "<Any>",
          "effect": "Strength:1",
          "source": null
        },
        {
          "key": null,
          "name": "Sub-Dermal Armour",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 4,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": "Armour:1",
          "source": null
        },
        {
          "key": null,
          "name": "Weapon Implant",
          "type": "Cybernetic",
          "subtype": "Implant",
          "value": 3,
          "rarity": "Rare",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Duelling Laspistol",
          "type": "Ranged Weapon",
          "subtype": "Las Weapon",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Las,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Hot-Shot Lasgun",
          "type": "Ranged Weapon",
          "subtype": "Las Weapon",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Las,Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Hot-Shot Laspistol",
          "type": "Ranged Weapon",
          "subtype": "Las Weapon",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Las,Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Lasconnon",
          "type": "Ranged Weapon",
          "subtype": "Las Weapon",
          "value": 9,
          "rarity": "Uncommon",
          "keywords": "Las,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Lasgun",
          "type": "Ranged Weapon",
          "subtype": "Las Weapon",
          "value": 3,
          "rarity": "Common",
          "keywords": "Las,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Laspistol",
          "type": "Ranged Weapon",
          "subtype": "Las Weapon",
          "value": 3,
          "rarity": "Common",
          "keywords": "Las,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Long Las",
          "type": "Ranged Weapon",
          "subtype": "Las Weapon",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Las,Imperium,Astra Militarum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Inferno Pistol",
          "type": "Ranged Weapon",
          "subtype": "Melta Weapon",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Melta,Imperium,Adepta Sororitas,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Meltagun",
          "type": "Ranged Weapon",
          "subtype": "Melta Weapon",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Melta,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Multi-Melta",
          "type": "Ranged Weapon",
          "subtype": "Melta Weapon",
          "value": 7,
          "rarity": "Rare",
          "keywords": "Melta,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Cyclone Missile Launcher",
          "type": "Ranged Weapon",
          "subtype": "Missile Launcher",
          "value": 11,
          "rarity": "Very Rare",
          "keywords": "Explosive,Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Missile Launcher",
          "type": "Ranged Weapon",
          "subtype": "Missile Launcher",
          "value": 4,
          "rarity": "Common",
          "keywords": "Explosive,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Frag Missile",
          "type": "Ranged Weapon",
          "subtype": "Missiles",
          "value": 4,
          "rarity": "Common",
          "keywords": "Explosive,Imperium,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Krak Missile",
          "type": "Ranged Weapon",
          "subtype": "Missiles",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Explosive,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "'Eavy Armour",
          "type": "Armour",
          "subtype": "Ork Armour",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Heavy,Primitive,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mega Armour",
          "type": "Armour",
          "subtype": "Ork Armour",
          "value": 9,
          "rarity": "Very Rare",
          "keywords": "Powered,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ork Flak",
          "type": "Armour",
          "subtype": "Ork Armour",
          "value": 2,
          "rarity": "Uncommon",
          "keywords": "Primitive,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ammo Grot",
          "type": "Tools & Equipment",
          "subtype": "Ork Equipment",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Dok Bag",
          "type": "Tools & Equipment",
          "subtype": "Ork Equipment",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Fightin' Juice",
          "type": "Tools & Equipment",
          "subtype": "Ork Equipment",
          "value": 4,
          "rarity": "Rare",
          "keywords": "Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mek Toolz",
          "type": "Tools & Equipment",
          "subtype": "Ork Equipment",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Big Choppa",
          "type": "Melee Weapon",
          "subtype": "Ork Melee Weapon",
          "value": 4,
          "rarity": "Rare",
          "keywords": "Blade,Ork,Two-Handed",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Chain Choppa",
          "type": "Melee Weapon",
          "subtype": "Ork Melee Weapon",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Chain,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Choppa",
          "type": "Melee Weapon",
          "subtype": "Ork Melee Weapon",
          "value": 2,
          "rarity": "Common",
          "keywords": "Blade,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Power Klaw",
          "type": "Melee Weapon",
          "subtype": "Ork Melee Weapon",
          "value": 8,
          "rarity": "Very Rare",
          "keywords": "Power Field,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Weirdboy Staff",
          "type": "Melee Weapon",
          "subtype": "Ork Melee Weapon",
          "value": 5,
          "rarity": "Very Rare",
          "keywords": "Force,Ork,Two-Handed",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Big Shoota",
          "type": "Ranged Weapon",
          "subtype": "Ork Ranged Weapon",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Projectile,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Burna",
          "type": "Ranged Weapon",
          "subtype": "Ork Ranged Weapon",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Fire,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Rokkit Launcha",
          "type": "Ranged Weapon",
          "subtype": "Ork Ranged Weapon",
          "value": 7,
          "rarity": "Rare",
          "keywords": "Explosive,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Shoota",
          "type": "Ranged Weapon",
          "subtype": "Ork Ranged Weapon",
          "value": 4,
          "rarity": "Uncommon",
          "keywords": "Projectile,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Slugga",
          "type": "Ranged Weapon",
          "subtype": "Ork Ranged Weapon",
          "value": 3,
          "rarity": "Common",
          "keywords": "Projectile,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Snazzgun",
          "type": "Ranged Weapon",
          "subtype": "Ork Ranged Weapon",
          "value": 8,
          "rarity": "Unique",
          "keywords": "Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Stikkbomb",
          "type": "Ranged Weapon",
          "subtype": "Ork Ranged Weapon",
          "value": 2,
          "rarity": "Uncommon",
          "keywords": "Explosive,Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Plasma Cannon",
          "type": "Ranged Weapon",
          "subtype": "Plasma Weapon",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Palsma,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Plasma Gun",
          "type": "Ranged Weapon",
          "subtype": "Plasma Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Palsma,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Plasma Pistol",
          "type": "Ranged Weapon",
          "subtype": "Plasma Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Palsma,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Death Cult Powerblade",
          "type": "Melee Weapon",
          "subtype": "Power Weapon",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Power Field,Imperium,Adeptus Ministorum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Omnissian Axe",
          "type": "Melee Weapon",
          "subtype": "Power Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Power Field,Imperium,Adeptus Mechanicus,Two-Handed",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Power Axe",
          "type": "Melee Weapon",
          "subtype": "Power Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Power Field,Imperium,Adeptus Astartes,Adeptus Mechanicus,Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Power Fist",
          "type": "Melee Weapon",
          "subtype": "Power Weapon",
          "value": 8,
          "rarity": "Very Rare",
          "keywords": "Power Field,Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Power Sword",
          "type": "Melee Weapon",
          "subtype": "Power Weapon",
          "value": 6,
          "rarity": "Rare",
          "keywords": "Power Field,Imperium,Aeldari",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Thunder Hammer",
          "type": "Melee Weapon",
          "subtype": "Power Weapon",
          "value": 9,
          "rarity": "Unique",
          "keywords": "Power Field,Imperium,Adeptus Astartes,Inquisition,Two-Handed",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Void Sabre",
          "type": "Melee Weapon",
          "subtype": "Power Weapon",
          "value": 8,
          "rarity": "Very Rare",
          "keywords": "Power Field,Aeldari,Anhrathe",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Heavy Power Armour",
          "type": "Armour",
          "subtype": "Powered",
          "value": 8,
          "rarity": "Very Rare",
          "keywords": "Heavy, Powered, Imperium, Inquisition",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ignatus Power Armour",
          "type": "Armour",
          "subtype": "Powered",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "Powered,Imperium,Inquisition",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Light Power Armour",
          "type": "Armour",
          "subtype": "Powered",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Powered,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Sororitas Powered Armour",
          "type": "Armour",
          "subtype": "Powered",
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Powered,Imperium,Adepta Sororitas",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Assault Cannon",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Projectile,Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Astartes Shotgun",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 7,
          "rarity": "Rare",
          "keywords": "Projectile,Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Astartes Sniper Rifle",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 6,
          "rarity": "Uncommon",
          "keywords": "Projectile,Imperium,Adeptus Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Autocannon",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 5,
          "rarity": "Common",
          "keywords": "Projectile,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Autogun",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 3,
          "rarity": "Common",
          "keywords": "Projectile,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Autopistol",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 3,
          "rarity": "Common",
          "keywords": "Projectile,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Combat Shotgun",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Projectile,Imperium",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Hand Cannon",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 4,
          "rarity": "Common",
          "keywords": "Projectile,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Heavy Stubber",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Projectile,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Shotgun",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 3,
          "rarity": "Common",
          "keywords": "Projectile,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Stubber",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 2,
          "rarity": "Common",
          "keywords": "Projectile,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Stubcannon",
          "type": "Ranged Weapon",
          "subtype": "Projectile Weapon",
          "value": 3,
          "rarity": "Common",
          "keywords": "Projectile,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Bionic Reconstruction",
          "type": "Cybernetic",
          "subtype": "Reconstruction",
          "value": "*",
          "rarity": "Common",
          "keywords": "<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ammunition Backpack",
          "type": "Weapon Upgrade",
          "subtype": "Reloads and Ammunition",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": null,
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ammunition Bandolier",
          "type": "Weapon Upgrade",
          "subtype": "Reloads and Ammunition",
          "value": 2,
          "rarity": "Common",
          "keywords": null,
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Hellfi re Bolt Rounds",
          "type": "Weapon Upgrade",
          "subtype": "Reloads and Ammunition",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": null,
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Kraken Bolt Rounds",
          "type": "Weapon Upgrade",
          "subtype": "Reloads and Ammunition",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": null,
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Manstopper Rounds",
          "type": "Weapon Upgrade",
          "subtype": "Reloads and Ammunition",
          "value": 5,
          "rarity": "Uncommon",
          "keywords": null,
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Reloads",
          "type": "Weapon Upgrade",
          "subtype": "Reloads and Ammunition",
          "value": 2,
          "rarity": "Common",
          "keywords": null,
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Vengeance Bolt Rounds",
          "type": "Weapon Upgrade",
          "subtype": "Reloads and Ammunition",
          "value": 7,
          "rarity": "Very Rare",
          "keywords": null,
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Astartes Combat Knife",
          "type": "Melee Weapon",
          "subtype": null,
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Blade,Imperium,Adeptus,Astartes",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Industiral Bludgeon",
          "type": "Melee Weapon",
          "subtype": null,
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Imperium,Ork,Scum,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Knife",
          "type": "Melee Weapon",
          "subtype": null,
          "value": 2,
          "rarity": "Common",
          "keywords": "Blade,Imperium,Aeldari,Ork,Scum,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mono Knife",
          "type": "Melee Weapon",
          "subtype": null,
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Blade,Imperium,Scum",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Psykana Mercy Blade",
          "type": "Melee Weapon",
          "subtype": null,
          "value": 2,
          "rarity": "Uncommon",
          "keywords": "Blade,Imperium,Adeptus Astra Telephatica",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Sword",
          "type": "Melee Weapon",
          "subtype": null,
          "value": 3,
          "rarity": "Common",
          "keywords": "Blade,Imperium,Aeldari,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Throwing Knife",
          "type": "Melee Weapon",
          "subtype": null,
          "value": 2,
          "rarity": "Common",
          "keywords": "Blade,Aeldari,Scum,<Any>",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Mek Toolz",
          "type": "Tools & Equipment",
          "subtype": null,
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Ork",
          "effect": null,
          "source": null
        },
        {
          "key": null,
          "name": "Ammunition Drum",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 3,
          "rarity": "Common",
          "keywords": "Imperium,Scum",
          "effect": "+1 Reload",
          "source": null
        },
        {
          "key": null,
          "name": "Autoloader",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium",
          "effect": "Reload as a Free Action",
          "source": null
        },
        {
          "key": null,
          "name": "Bayonet Lug",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 1,
          "rarity": "Common",
          "keywords": "<Any>",
          "effect": "Counts as Knife, Free Upgrade",
          "source": null
        },
        {
          "key": null,
          "name": "Chain Bayonet",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 4,
          "rarity": "Rare",
          "keywords": "Imperium,Chaos",
          "effect": "Counts as Chain Bayonet",
          "source": null
        },
        {
          "key": null,
          "name": "Combi-Weapon",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 6,
          "rarity": "Rare",
          "keywords": "Imperium,Chaos,Scum",
          "effect": "Combine 2 Weapon",
          "source": null
        },
        {
          "key": null,
          "name": "Distinction",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": "+1 D to Intimidation, Free Upgrade",
          "source": null
        },
        {
          "key": null,
          "name": "Duelling Grip",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "<Any>",
          "effect": "+1 D to Attacks, only one handed Weapon",
          "source": null
        },
        {
          "key": null,
          "name": "Gene-Grip Bio-Veritor",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 5,
          "rarity": "Rare",
          "keywords": "Imperium",
          "effect": "Locked by Users Genetics",
          "source": null
        },
        {
          "key": null,
          "name": "Master-Crafted",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 7,
          "rarity": "Very Rare",
          "keywords": "<Any>",
          "effect": "Gain Steadfast and +2 D to Attacks",
          "source": null
        },
        {
          "key": null,
          "name": "Megathoule Accelerator",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 6,
          "rarity": "Very Rare",
          "keywords": "Imperium,Astra Militarum",
          "effect": "+2 Salvo, Loses Steadfast, only Las Weapon",
          "source": null
        },
        {
          "key": null,
          "name": "Monoscope",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 4,
          "rarity": "Rare",
          "keywords": "Imperium,Astra Militarum",
          "effect": "Reduce Range DN by 2",
          "source": null
        },
        {
          "key": null,
          "name": "Percussive Muzzle Brake",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Imperium,Scum",
          "effect": "+1 Salvo, only non heavy projectile Weapon",
          "source": null
        },
        {
          "key": null,
          "name": "Preysense Sight",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 6,
          "rarity": "Rare",
          "keywords": "Imperium,Scum,<Any>",
          "effect": "See in bitch black",
          "source": null
        },
        {
          "key": null,
          "name": "Red-Dot Sight",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 5,
          "rarity": "Uncommon",
          "keywords": "Imperium,Scum",
          "effect": "+1 D to Ranged Attacks",
          "source": null
        },
        {
          "key": null,
          "name": "Silencer",
          "type": "Weapon Upgrade",
          "subtype": null,
          "value": 3,
          "rarity": "Uncommon",
          "keywords": "Imperium,Scum,<Any>",
          "effect": "+4 to DN for Awareness Tests",
          "source": null
        }
      ],
      archetypeWargearRepository: [
        // Imperium
        {
          name: 'Ministorium Prist',
          options: [
            { name: 'Laspistol' },
            { name: 'Rosarius' },
            { name: 'Knife' },
            { name: 'Clothing', variant: 'Ministorum robes' },
            { name: 'Missionary kit' },
          ],
        },
        {
          name: 'Crusader',
          options: [
            { name: 'Power Sword' },
            { name: 'Storm Shield' },
            { name: 'Carapace Armour' },
            { name: 'Clothing', variant: 'Ministorum robes' },
          ],
        },
        {
          name: 'Death Cult Assassin',
          options: [
            { name: 'Bodyglove' },
            { name: 'Death Cult Powerblade' },
            { name: 'Death Cult Powerblade' },
            { name: 'Knife' },
            { name: 'Laspistol' },
            { name: 'Doses of stimm', amount: 3 },
          ],
        },
        {
          name: 'Sister of Battle',
          options: [
            { name: 'Sororitas Powered Armour' },
            { name: 'Chaplet Ecclisiasticus' },
            {
              name: 'Either a boltgun OR a chainsword and bolt pistol.',
              selected: 'Boltgun',
              options: [
                { name: 'Boltgun' },
                { name: 'Chainsword and Bold pistol' },
              ],
            },
            { name: 'Clothing', variant: 'Sororitas vestments' },
            { name: 'Writing kit' },
            { name: 'Copy of the Rule of the Sororitas' },
          ],
        },
        {
          name: 'Sister Hospitaller',
          options: [
            { name: 'Sororitas Powered Armour' },
            { name: 'Chirurgeon\'s Tools' },
            { name: 'Laspistol' },
            { name: 'Clothing', variant: 'Sororitas vestments' },
            { name: 'Copy of the Rule of the Sororitas' },
          ],
        },
        {
          name: 'Commissar',
          options: [
            { name: 'Flak Coat' },
            { name: 'Bold pistol' },
            { name: 'Chain Sword' },
            { name: 'Guard issue mess kit' },
            { name: 'Blanket' },
            { name: 'Grooming kit' },
            { name: 'Uplifting Primer' },
            { name: 'Ration Packs', amount: 3 },
          ],
        },
        {
          name: 'Imperial Guardsman',
          options: [
            { name: 'Flak Armour' },
            { name: 'Lasgun' },
            { name: 'Knife' },
            { name: 'Guard issue mess kit' },
            { name: 'Blanket' },
            { name: 'Grooming kit' },
            { name: 'Uplifting Primer' },
            { name: 'Ration Packs', amount: 3 },
          ],
        },
        {
          name: 'Tempestus Scion',
          options: [
            { name: 'Carapace Armour' },
            { name: 'Hot-Shot Lasgun' },
            { name: 'Grav-chute' },
            { name: 'Knife' },
            { name: 'Guard issue mess kit' },
            { name: 'Blanket' },
            { name: 'Grooming kit' },
            { name: 'Uplifting Primer' },
            { name: 'Ration Packs', amount: 3 },
          ],
        },
        {
          name: 'Inquisitorial Acolyte',
          options: [
            { name: 'Flak Armour' },
            {
              name: 'Range weapon of value 5 or less of up to Uncommon rarity (must have the Imperium keyword',
              selected: undefined,
              options: [
                {
                  query: (item) => {
                    const valueReq = item.value <= 5;
                    const rarityReq = ['Uncommon'].includes(item.rarity);
                    const keywordReq = ( item.keywords ) ? item.keywords.split(',').includes('Imperium') : false;
                    const typeReq = item.type === 'Ranged Weapon';
                    return (valueReq && rarityReq && keywordReq && typeReq);
                  },
                },
              ],
            },
            { name: 'Knife' },
          ],
        },
        {
          name: 'Inquisitorial Adept',
          options: [
            { name: 'Flak Armour' },
            { name: 'Laspistol' },
            { name: 'Knife' },
            { name: 'Auto quill' },
            { name: 'Data-slate' },
            { name: 'Ancient Records', amount: 3 },
          ],
        },
        {
          name: 'Inquisitor',
          options: [
            {
              name: 'Choice of Flak Coat, Ignatus Power Armour or Light Power Armour',
              selected: undefined,
              options: [
                { name: 'Flak Coat' },
                { name: 'Ignatus Power Armour' },
                { name: 'Light Power Armour' },
              ],
            },
            {
              name: 'Ranged weapon up to availability 7 and rarity Very Rare.',
              selected: undefined,
              options: [
                {
                  query: item => (
                    item.value <= 7
                    && ['Uncommon', 'Common', 'Rare', 'Very Rare'].includes(item.rarity)
                    && item.type.includes('Ranged Weapon')
                  ),
                },
              ],
            },
            {
              name: 'Melee weapon up to availability 7 and rarity Very Rare.',
              selected: undefined,
              options: [
                {
                  query: item => (
                    item.value <= 7
                    && ['Uncommon', 'Common', 'Rare', 'Very Rare'].includes(item.rarity)
                    && item.type.includes('Melee Weapon')
                  ),
                },
              ],
            },
            { name: 'Symbol of authority' },
          ],
        },
        {
          name: 'Rogue Trader',
          options: [
            {
              name: 'Choice of Flak Coat, carapace armour or Light Power Armour',
              selected: undefined,
              options: [
                { name: 'Flak Coat' },
                { name: 'Carapace Armour' },
                { name: 'Light Power Armour' },
              ],
            },
            {
              name: 'Ranged weapon up to value Tier+4 and rarity Rare.',
              selected: undefined,
              options: [
                {
                  query: item => (
                    item.value <= (this.settingTier + 4)
                    && ['Uncommon', 'Common', 'Rare'].includes(item.rarity)
                    && item.type.includes('Ranged Weapon')
                  ),
                },
              ],
            },
            {
              name: 'Melee weapon up to value Tier+4 and rarity Rare.',
              selected: undefined,
              options: [
                {
                  query: item => (
                    item.value <= this.settingTier + 4
                    && ['Uncommon', 'Common', 'Rare'].includes(item.rarity)
                    && item.type.includes('Melee Weapon')
                  ),
                },
              ],
            },
            { name: 'Imperial Frigate' },
          ],
        },
        {
          name: 'Sanctioned Psyker',
          options: [
            { name: 'Laspistol' },
            { name: 'Force rod' },
            { name: 'Psykana Mercy Blade' },
            { name: 'Guard issue mess kit' },
            { name: 'Blanket' },
            { name: 'Grooming kit' },
            { name: 'Ration Packs', amount: 2 },
          ],
        },
        {
          name: 'Space Marine Scout',
          options: [
            { name: 'Scout Armour' },
            {
              name: 'Either a boltgun OR a bolt pistol.',
              selected: 'Boltgun',
              options: [
                { name: 'Boltgun' },
                { name: 'Bold Pistol' },
              ],
            },
            { name: 'Astartes Combat Knife' },
            { name: 'Frag Grenades', amount: 3 },
            { name: 'Krak Grenades', amount: 3 },
          ],
        },
        {
          name: 'Tactical Space Marine',
          options: [
            { name: 'Aquila Mk VII' },
            { name: 'Boltgun' },
            { name: 'Bolt Pistol' },
            { name: 'Astartes Combat Knife' },
            { name: 'Frag Grenades', amount: 3 },
            { name: 'Krak Grenades', amount: 3 },
          ],
        },
        {
          name: 'Primaris Intercessor',
          options: [
            { name: 'Mark X Tacticus Power Armour' },
            {
              name: 'Either a bolt rifle OR a heavy bolt pistol.',
              selected: 'Bolt Rifle',
              options: [
                { name: 'Bolt Rifle' },
                { name: 'Heavy Bold pistol' },
              ],
            },
            { name: 'Astartes Combat Knife' },
            { name: 'Frag Grenades', amount: 3 },
            { name: 'Krak Grenades', amount: 3 },
          ],
        },
        {
          name: 'Tech-Priest',
          options: [
            { name: 'Light Power Armour' },
            { name: 'Ommnissian Axe' },
            { name: 'Laspistol' },
            { name: 'Mechandrites (Servo-Arm)' },
            {
              name: 'One augmetic of your choice.',
              selected: undefined,
              options: [
                { query: item => ( item.type === 'Cybernetic' ), },
              ],
            },
            {
              name: 'One augmetic of your choice.',
              selected: undefined,
              options: [
                { query: item => ( item.type === 'Cybernetic' ), },
              ],
            },
          ],
        },
        {
          name: 'Skitarius',
          options: [
            { name: 'Skatarii Auto-Cuirass' },
            { name: 'Galvanic Rifle' },
          ],
        },
        {
          name: 'Ganger',
          options: [
            {
              name: 'Choice of Laspistol, Autopistol, Hand Cannon or Stub Gun.',
              selected: 'Laspistol',
              options: [
                { name: 'Laspistol' },
                { name: 'Autpistol' },
                { name: 'Hand Cannon' },
                { name: 'Stub Gun' },
              ],
            },
            {
              name: 'Choice of Knife or Sword.',
              selected: 'Knife',
              options: [
                { name: 'Knife' },
                { name: 'Sword' },
              ],
            },
            { name: 'Bedroll' },
            { name: 'Canteen' },
            { name: 'Clothing', variant: 'Gang Colours' },
          ],
        },
        {
          name: 'Scavvy',
          options: [
            {
              name: 'Choice of Laspistol or Autopistol.',
              selected: 'Laspistol',
              options: [
                { name: 'Laspistol' },
                { name: 'Autpistol' },
              ],
            },
            { name: 'Knife' },
            { name: 'Bedroll' },
            { name: 'Canteen' },
            { name: 'Clothing', variant: 'Tattered' },
          ],
        },
        {
          name: 'Desperado',
          options: [
            {
              name: 'Choce of boltgun OR a chainsword and bolt pistol.',
              selected: 'Boltgun',
              options: [
                { name: 'Boltgun' },
                { name: 'Chainsword and Bold pistol' },
              ],
            },
            { name: 'Flak Coat' },
            { name: 'Prysense Googles' },
            { name: 'Various Maps' },
            { name: 'Combi Tool' },
          ],
        },
        // Renegade
        {
          name: 'Cultist',
          options: [
            {
              name: 'Choce of lasgun OR autogun.',
              selected: 'Lasgun',
              options: [
                { name: 'Lasgun' },
                { name: 'Autogun' },
              ],
            },
            { name: 'Knife' },
            { name: 'Symbol of Authority', variant: 'Unholy icon' },
            { name: 'Guard issue mess kit' },
            { name: 'blanket', variant: 'tattered' },
          ],
        },
        {
          name: 'Heretek',
          options: [
            { name: 'Laspistol' },
            { name: 'Mechandrites (Servo-Arm)' },
            {
              name: 'One augmetic of your choice.',
              selected: undefined,
              options: [
                { query: item => ( item.type === 'Cybernetic' ), },
              ],
            },
            {
              name: 'One augmetic of your choice.',
              selected: undefined,
              options: [
                { query: item => ( item.type === 'Cybernetic' ), },
              ],
            },
          ],
        },
        {
          name: 'Chaos Space Marine',
          options: [
            { name: 'Aquila Mk VII' },
            { name: 'Boltgun' },
            { name: 'Bolt Pistol' },
            { name: 'Astartes Combat Knife' },
            { name: 'Frag Grenades', amount: 3 },
            { name: 'Krak Grenades', amount: 3 },
          ],
        },
        // Aeldari
        {
          name: 'Corsair',
          options: [
            { name: 'Corsair Armour' },
            { name: 'Shuriken Pistol' },
            { name: 'Lasblaster' },
            { name: 'Spirit Stone' },
            { name: 'Plasma Grenades', amount: 3 },
            { name: 'Void Suite' },
          ],
        },
        {
          name: 'Ranger',
          options: [
            { name: 'Chameleoline Cloak' },
            { name: 'Eldar Mesh Armour' },
            { name: 'Ranger Long Rifle' },
            { name: 'Shuriken Pistol' },
            { name: 'Spirit Stone' },
            { name: 'Knife' },
            { name: 'Bedroll' },
            { name: 'Blanket' },
          ],
        },
        {
          name: 'Warlock',
          options: [
            { name: 'Rune Armour' },
            { name: 'Shuriken Pistol' },
            { name: 'Witchblade' },
            { name: 'A set of Wraithbone Runes' },
            { name: 'Spirit Stone' },
          ],
        },
        // Ork
        {
          name: 'Boy',
          options: [
            { name: 'Shoota' },
            { name: 'Slugga' },
            { name: 'Choppa' },
          ],
        },
        {
          name: 'Kommando',
          options: [
            { name: 'Shoota' },
            { name: 'Slugga' },
            { name: 'Choppa' },
            { name: 'Stikkbombs' },
          ],
        },
        {
          name: 'Nob',
          options: [
            { name: '\'Eavy Armour' },
            { name: 'Kustom Slugga' },
            { name: 'Kustom Choppa' },
          ],
        },
      ],
    };
  },
};
